### ISSUE TITLE
Use of undeclared variable

### ISSUE THREAD

**Issue by YossiMH** [tertle/com.bovinelabs.analyzers#3]
After importing the package into a Unity 2019.1.0f2 project I see the following compiler error:

`Library\PackageCache\com.bovinelabs.analyzers@1be1c4a29065fbce6d75b2b262ba6d2261dcace1\ProjectFilesGeneration.cs(31,49): error CS0103: The name 'contents' does not exist in the current context`, and indeed, there does not appear any static field or local variable with the name `contents` in that scope.

**Comment by tertle** [comment]
Thanks for the report. I haven't been using visual studios (been using rider) so this slipped past me. 

I have pushed an update that should fix this.
